environment: production
vpc_cidr_block: "172.26.0.0/16"
vpc_name: algadelivery-vpc-prod
instance_type: t3.small

subnet_pub_config:
  public_a:
    cidr_block: "172.26.1.0/24"
    az: a
  public_b:
    cidr_block: "172.26.2.0/24"
    az: b
  public_c:
    cidr_block: "172.26.3.0/24"
    az: c

subnet_pvt_management_config:
  private_a:
    cidr_block: "172.26.4.0/24"
    az: a
  private_b:
    cidr_block: "172.26.5.0/24"
    az: b
  private_c:
    cidr_block: "172.26.6.0/24"
    az: c

subnet_pvt_cluster_config:
  private_a:
    cidr_block: "172.26.7.0/24"
    az: a
  private_b:
    cidr_block: "172.26.8.0/24"
    az: b
  private_c:
    cidr_block: "172.26.9.0/24"
    az: c
